# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
  
    bump_version_code()

    gradle(task: "clean assembleTreetrackerDebug")
    crashlytics(groups: "all-testers")
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


  desc "Submit a new JustDigIt Beta Build to Crashlytics Beta"
  lane :justdigit_beta do
  
    bump_version_code()

    git_commit(path: "./app/build.gradle", message: "Version Bump")

    gradle(task: "clean assembleJustdigitDebug")
    crashlytics(groups: "all-testers")
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Bump version code"
  lane :bump_version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end
end
