name: Treetracker Android App CI PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, release* ]

jobs:
  build:
    name: test and assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Generate dummy property file
        run: |
          echo "#Treetracker API Keys
          treetracker_client_id=dummy-id
          treetracker_client_secret=dummy-secret
          s3_dev_identity_pool_id=dummy-pool-id-dev
          s3_test_identity_pool_id=dummy-pool-id-test" > treetracker.keys.properties
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Build Debug APK
        run: bash ./gradlew :app:assembleDebug
      - name: Delete dummy property file
        run: rm treetracker.keys.properties
